objective:
  - Bilevel Optimization
dataset:
  - covtype
solver:
  - AmIGO[batch_size=64,eval_freq=2048,framework=none,n_inner_steps=10,outer_ratio=0.1,step_size=0.03125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - MRBO[batch_size=64,eta=0.5,eval_freq=2048,framework=none,n_shia_steps=10,outer_ratio=0.01,step_size=1.0,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - VRBO[batch_size=64,eval_freq=2048,framework=none,n_inner_steps=10,n_shia_steps=10,outer_ratio=0.01,period_frac=0.5,step_size=0.25,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - StocBiO[batch_size=64,eval_freq=2048,framework=none,n_inner_steps=10,n_shia_steps=10,outer_ratio=0.01,step_size=0.0625,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SRBA[batch_size=64,eval_freq=2048,framework=none,outer_ratio=0.01,period_frac=8.0,step_size=0.03125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - PZOBO[eval_freq=1,framework=none,mu=0.1,n_gaussian_vectors=1,n_inner_steps=10,outer_ratio=0.01,step_size=0.25,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - Optuna[random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
  - FSLA[batch_size=64,eval_freq=2048,framework=none,outer_ratio=0.01,step_size=1.0,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SUSTAIN[batch_size=64,eta=0.5,eval_freq=2048,framework=none,n_hia_steps=10,outer_ratio=0.01,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SOBA[batch_size=64,eval_freq=2048,framework=none,outer_ratio=0.01,step_size=1.0,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - TTSA[batch_size=64,eval_freq=2048,framework=none,n_hia_steps=10,outer_ratio=0.01,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - BSA[batch_size=64,eval_freq=2048,framework=none,n_hia_steps=10,n_inner_steps=10,outer_ratio=0.01,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SFFBA[batch_size=64,eval_freq=512,inner_size=0.5,assis_ratio=1.0,outer_ratio=0.0001,step_size=0.01,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
  - MSEBA[batch_size=64,eval_freq=512,inner_size=0.2,assis_ratio=1.0,outer_ratio=0.001,step_size=0.01,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
  - SPABA[batch_size=64,eval_freq=96,inner_size=0.4,assis_ratio=1.0,outer_ratio=0.001,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
n-repetitions: 1
max-runs: 64000
timeout: 900
output: covtype_best_params

