objective:
  - Bilevel Optimization
dataset:
  - covtype
solver:
  - AmIGO[batch_size=64,n_inner_steps=[10],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - BSA[batch_size=64,n_inner_steps=[10],n_hia_steps=[10],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - FSLA[batch_size=64,eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - MRBO[batch_size=64,n_shia_steps=[10],eta=[0.5],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SABA[batch_size=64,eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SOBA[batch_size=[64],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - StocBiO[batch_size=64,n_inner_steps=[10],n_shia_steps=[10],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SUSTAIN[batch_size=64,n_hia_steps=[10],eta=[0.5],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - TTSA[batch_size=64,n_hia_steps=[10],eval_freq=2048,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SRBA[batch_size=64,period_frac=[0.5, 8., 64., 512.],eval_freq=[2048],step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - VRBO[batch_size=64,period_frac=[0.5, 8., 64., 512.],eval_freq=[2048],n_shia_steps=10,step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.],outer_ratio=[0.01, 0.1, 1., 10.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=nonen n_inner_steps=10]
  - PZOBO[eval_freq=1,outer_ratio=[0.01, 0.1, 1., 10.],step_size=[0.03125, 0.0625, 0.125, 0.25, 0.5, 1.], random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], mu=[.01, .1], n_gaussian_vectors=[1, 10],framework=none]
  - Optuna[random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
n-repetitions: 1
max-runs: 64000
timeout: 900
output: covtype
