objective:
  - Bilevel Optimization
dataset:
  - mnist[ratio=0.5]
solver:
  - AmIGO[batch_size=64,eval_freq=512,framework=none,n_inner_steps=10,outer_ratio=1e-05,step_size=0.001,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - MRBO[batch_size=64,eta=0.5,eval_freq=512,framework=none,n_shia_steps=10,outer_ratio=0.0001,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - VRBO[batch_size=64,eval_freq=512,framework=none,n_inner_steps=10,n_shia_steps=10,outer_ratio=0.0001,period_frac=0.5,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SABA[batch_size=64,eval_freq=512,framework=none,init_memory=zero,outer_ratio=0.001,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - StocBiO[batch_size=64,eval_freq=512,framework=none,n_inner_steps=10,n_shia_steps=10,outer_ratio=1e-05,step_size=0.01,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SRBA[batch_size=64,eval_freq=512,framework=none,outer_ratio=1e-05,period_frac=512.0,step_size=0.001,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - PZOBO[eval_freq=1,framework=none,mu=0.01,n_gaussian_vectors=10,n_inner_steps=10,outer_ratio=0.01,step_size=0.01,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - Optuna[random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
  - FSLA[batch_size=64,eval_freq=64,framework=none,outer_ratio=0.0001,step_size=1.0,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SUSTAIN[batch_size=64,eta=0.5,eval_freq=512,framework=none,n_hia_steps=10,outer_ratio=0.0001,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - SOBA[batch_size=64,eval_freq=512,framework=none,outer_ratio=0.0001,step_size=1.0,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - TTSA[batch_size=64,eval_freq=512,framework=none,n_hia_steps=10,outer_ratio=1e-05,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
  - BSA[batch_size=64,eval_freq=512,framework=none,n_hia_steps=10,n_inner_steps=10,outer_ratio=1e-05,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]
n-repetitions: 10
max-runs: 64000
timeout: 7200
output: datacleaning0_5_best_params
