objective:
  - Bilevel Optimization
dataset:
  - mnist[oracle=datacleaning,random_state=32,ratio=0.5]
solver:
  - AmIGOAmIGO[batch_size=64,eval_freq=64,framework=none,n_inner_steps=10,outer_ratio=1e-06,step_size=0.001,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
  - StocBiO[batch_size=64,eval_freq=64,framework=none,n_inner_steps=10,n_shia_steps=10,outer_ratio=1e-05,step_size=0.01,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - SABA[batch_size=64,eval_freq=512,framework=none,mode_init_memory=zero,outer_ratio=0.001,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - MRBO[batch_size=64,eta=0.5,eval_freq=64,framework=none,n_shia_steps=10,outer_ratio=1e-06,step_size=1.0,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - SRBA[batch_size=64,eval_freq=512,framework=none,outer_ratio=1e-05,period_frac=512.0,step_size=0.001,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - VRBO[batch_size=64,eval_freq=4,framework=none,n_inner_steps=10,n_shia_steps=10,outer_ratio=1e-05,period_frac=0.01,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - F2SA[batch_size=64,delta_lmbda=1.0,eval_freq=64,framework=none,lmbda0=1.0,n_inner_steps=10,outer_ratio=0.0001,step_size=0.1,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n-repetitions: 1
max-runs: 64000
timeout: 900
output: datacleaning0_5
