objective:
  - Bilevel Optimization
dataset:
  - mnist[oracle=datacleaning,random_state=32,ratio=0.5]
solver:
  - AmIGO[batch_size=64,eval_freq=64,n_inner_steps=10,outer_ratio=[1e-6,1e-5,1e-4,1e-3],step_size=[0.001,0.01,0.1,1.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]  # 4 * 4 * 10 = 160
  - StocBiO[batch_size=64,eval_freq=64,n_inner_steps=10,n_shia_steps=10,outer_ratio=[1e-6,1e-5,1e-4,1e-3],step_size=[0.001,0.01,0.1,1.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]  # 4 * 4 * 10 = 160
  - SABA[batch_size=64,eval_freq=512,outer_ratio=[1e-6,1e-5,1e-4,1e-3],step_size=[0.001,0.01,0.1,1.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]  # 4 * 4 * 10 = 160
  - MRBO[batch_size=64,eta=0.5,eval_freq=64,n_shia_steps=10,outer_ratio=[1e-6,1e-5,1e-4,1e-3],step_size=[0.001,0.01,0.1,1.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]  # 4 * 4 * 10 = 160
  - SRBA[batch_size=64,period_frac=[0.5, 8.,64.,512.],eval_freq=512,step_size=[0.001,0.01,0.1,1.],outer_ratio=[1e-6,1e-5,1e-4,1e-3],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]  # 4 * 4 * 4 * 10 = 640 
  - VRBO[batch_size=64,period_frac=[.01, .1, 0.5, 8.,64.,512.],eval_freq=4,step_size=[0.001,0.01,0.1,1.],outer_ratio=[1e-6,1e-5,1e-4,1e-3],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=none]  # 4 * 6 * 4 * 10 = 960
  - F2SA[batch_size=64,delta_lmbda=[.01,0.1,1.],eval_freq=64,framework=none,lmbda0=1.0,n_inner_steps=10,outer_ratio=[1e-6,1e-5,1e-4,1e-3],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],step_size=[0.001,0.01,0.1,1.]]  # 3 * 4 * 4 * 10 = 480
n-repetitions: 1
max-runs: 64000
timeout: 900
output: datacleaning0_5
