objective:
  - Bilevel Optimization[model=None,n_reg=full,numba=False,reg=exp,task=datacleaning]
dataset:
  - mnist[ratio=0.5]
solver:
  - VRBO[batch_size=[64],period_frac=[0.5, 8.,64.,512.],eval_freq=[256],step_size=[0.001,0.01,0.1,1.],outer_ratio=[1e-5,1e-4,0.001,0.01,0.1,1.],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
n-repetitions: 1
max-runs: 64000
timeout: 900
output: datacleaning0_5_vrbo
  