objective:
  - Bilevel Optimization
dataset:
  - ijcnn1
solver:
  - AmIGO[batch_size=64,eval_freq=131072,framework=numba,n_inner_steps=10,outer_ratio=0.31622776601683794,step_size=0.125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - MRBO[batch_size=64,eta=0.5,eval_freq=131072,framework=numba,n_shia_steps=10,outer_ratio=0.03162277660168379,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - VRBO[batch_size=64,eval_freq=131072,framework=numba,n_inner_steps=10,n_shia_steps=10,outer_ratio=1.0,period_frac=0.5,step_size=0.0625,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - SABA[batch_size=64,eval_freq=131072,framework=numba,init_memory=zero,outer_ratio=1.0,step_size=0.125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - StocBiO[batch_size=64,eval_freq=131072,framework=numba,n_inner_steps=10,n_shia_steps=10,outer_ratio=1.0,step_size=0.125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - SRBA[batch_size=64,eval_freq=131072,framework=numba,outer_ratio=1.0,period_frac=0.5,step_size=0.25,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - PZOBO[eval_freq=1,framework=numba,mu=0.01,n_gaussian_vectors=1,n_inner_steps=10,outer_ratio=0.31622776601683794,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - Optuna[random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
  - FSLA[batch_size=64,eval_freq=131072,framework=numba,outer_ratio=0.01,step_size=0.03125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - SUSTAIN[batch_size=64,eta=0.5,eval_freq=131072,framework=numba,n_hia_steps=10,outer_ratio=0.1,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - SOBA[batch_size=64,eval_freq=131072,framework=numba,outer_ratio=0.01,step_size=0.03125,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - TTSA[batch_size=64,eval_freq=131072,framework=numba,n_hia_steps=10,outer_ratio=0.03162277660168379,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
  - BSA[batch_size=64,eval_freq=131072,framework=numba,n_hia_steps=10,n_inner_steps=10,outer_ratio=0.01,step_size=0.5,random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],framework=numba]
n-repetitions: 1
max-runs: 1500
timeout: 900
output: ijcnn1_best_params
