objective:
  - Bilevel Optimization[model=logreg,n_reg=full,numba=True,reg=exp,task=classif]
dataset:
  - ijcnn1
solver:
  - VRBO[batch_size=[64],period_frac=[0.5, 8.,64.,512.],eval_freq=[131072],step_size=[0.125, 0.25, 0.5, 1.0, 2.0],outer_ratio=[0.01, 0.03162277660168379, 0.1, 0.31622776601683794, 1.0],random_state=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
n-repetitions: 1
max-runs: 1500
timeout: 900
output: ijcnn1_vrbo