objective:
  - Bilevel Optimization
dataset:
  - simulated[L_cross_inner=0.1,L_cross_outer=0.1,mu_inner=[.1],n_samples_inner=[32768],n_samples_outer=[1024],dim_inner=100,dim_outer=10] # 1
solver:
  - AmIGO[batch_size=64,eval_freq=16,n_inner_steps=10,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 80
  - BOME[outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],eta=[5e-1,5,5e-2],random_state=[1,2,3,4,5,6,7,8,9,10]] # 240
  - BSA[batch_size=64,eval_freq=64,n_inner_steps=10,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 80
  - FSLA[batch_size=64,eval_freq=16,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 80
  - jaxopt_gd[inner_solver=['gd','lbfgs'],step_size_outer=[.001,.01,.1,1.],n_inner_steps=[10,100]] # 16
  - jaxopt_itd[inner_solver=['gd','lbfgs'],step_size_outer=[.001,.01,.1,1.],n_inner_steps=[10,100],warm_start=[True,False]] # 32
  - OPTUNA
  - PZOBO[n_gaussian_vectors=[10,100],mu=1e-2,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 160
  - SOBA[batch_size=64,eval_freq=16,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]]
  - SUSTAIN[batch_size=64,eval_freq=16,n_hia_steps=10,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]]
  - TTSA[batch_size=64,eval_freq=64,n_hia_steps=10,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]]
  - MRBO[batch_size=64,eta=0.5,eval_freq=16,n_shia_steps=10,outer_ratio=[0.1, 1., 10],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 80
  - SABA[batch_size=64,eval_freq=64,mode_init_memory=zero,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]]  # 80
  - SRBA[batch_size=64,eval_freq=64,outer_ratio=[0.1, 1.,10,100],period_frac=[0.5, 8.,64.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 240
  - StocBiO[batch_size=64,eval_freq=16,n_inner_steps=10,n_shia_steps=10,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 80
  - VRBO[batch_size=64,eval_freq=2,n_inner_steps=10,n_shia_steps=10,outer_ratio=[0.1,1.,10.,100.],period_frac=[.01, .1, 0.5, 8.,64],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10]] # 400
  - F2SA[batch_size=64,eval_freq=16,n_inner_steps=10,outer_ratio=[0.1,1.,10.,100.],step_size=[.01,.1],random_state=[1,2,3,4,5,6,7,8,9,10],delta_lmbda=[.01,0.1,1.],lmbda0=1] # 240
n-repetitions: 1
max-runs: 64000
timeout: 900
output: quadratic
